package com.waffiq.countryPicker.countryPicker.model

import com.waffiq.countryPicker.countryPicker.R

object Helper {
  val countryList = listOf(
    Country("Afghanistan", "+93", "AF", R.drawable.flag_af),
    Country("Albania", "+355", "AL", R.drawable.flag_al),
    Country("Algeria", "+213", "DZ", R.drawable.flag_dz),
    Country("American Samoa", "+1-684", "AS", R.drawable.flag_as),
    Country("Andorra", "+376", "AD", R.drawable.flag_ad),
    Country("Angola", "+244", "AO", R.drawable.flag_ao),
    Country("Anguilla", "+1-264", "AI", R.drawable.flag_ai),
    Country("Antarctica", "+672", "AQ", R.drawable.flag_aq),
    Country("Antigua and Barbuda", "+1-268", "AG", R.drawable.flag_ag),
    Country("Argentina", "+54", "AR", R.drawable.flag_ar),
    Country("Armenia", "+374", "AM", R.drawable.flag_am),
    Country("Aruba", "+297", "AW", R.drawable.flag_aw),
    Country("Australia", "+61", "AU", R.drawable.flag_au),
    Country("Austria", "+43", "AT", R.drawable.flag_at),
    Country("Azerbaijan", "+994", "AZ", R.drawable.flag_az),
    Country("Bahamas (the)", "+1-242", "BS", R.drawable.flag_bs),
    Country("Bahrain", "+973", "BH", R.drawable.flag_bh),
    Country("Bangladesh", "+880", "BD", R.drawable.flag_bd),
    Country("Barbados", "+1-246", "BB", R.drawable.flag_bb),
    Country("Belarus", "+375", "BY", R.drawable.flag_by),
    Country("Belgium", "+32", "BE", R.drawable.flag_be),
    Country("Belize", "+501", "BZ", R.drawable.flag_bz),
    Country("Benin", "+229", "BJ", R.drawable.flag_bj),
    Country("Bermuda", "+1-441", "BM", R.drawable.flag_bm),
    Country("Åland Islands", "+358-18", "AX", R.drawable.flag_ax),
    Country("Bhutan", "+975", "BT", R.drawable.flag_bt),
    Country("Bolivia (Plurinational State of)", "+591", "BO", R.drawable.flag_bo),
    Country("Bonaire, Sint Eustatius and Saba", "+599", "BQ", R.drawable.flag_bq),
    Country("Bosnia and Herzegovina", "+387", "BA", R.drawable.flag_ba),
    Country("Botswana", "+267", "BW", R.drawable.flag_bw),
    Country("Bouvet Island", "+47", "BV", R.drawable.flag_bv),
    Country("Brazil", "+55", "BR", R.drawable.flag_br),
    Country("British Indian Ocean Territory", "+246", "IO", R.drawable.flag_io),
    Country("Brunei Darussalam", "+673", "BN", R.drawable.flag_bn),
    Country("Bulgaria", "+359", "BG", R.drawable.flag_bg),
    Country("Burkina Faso", "+226", "BF", R.drawable.flag_bf),
    Country("Burundi", "+257", "BI", R.drawable.flag_bi),
    Country("Cabo Verde", "+238", "CV", R.drawable.flag_cv),
    Country("Cambodia", "+855", "KH", R.drawable.flag_kh),
    Country("Cameroon", "+237", "CM", R.drawable.flag_cm),
    Country("Canada", "+1", "CA", R.drawable.flag_ca),
    Country("Cayman Islands (the)", "+1-345", "KY", R.drawable.flag_ky),
    Country("Central African Republic (the)", "+236", "CF", R.drawable.flag_cf),
    Country("Chad", "+235", "TD", R.drawable.flag_td),
    Country("Chile", "+56", "CL", R.drawable.flag_cl),
    Country("China", "+86", "CN", R.drawable.flag_cn),
    Country("Christmas Island", "+61", "CX", R.drawable.flag_cx),
    Country("Cocos (Keeling) Islands (the)", "+61", "CC", R.drawable.flag_cc),
    Country("Colombia", "+57", "CO", R.drawable.flag_co),
    Country("Comoros (the)", "+269", "KM", R.drawable.flag_km),
    Country("Congo (the Democratic Republic of the)", "+243", "CD", R.drawable.flag_cd),
    Country("Congo", "+242", "CG", R.drawable.flag_cg),
    Country("Cook Islands", "+682", "CK", R.drawable.flag_ck),
    Country("Costa Rica", "+506", "CR", R.drawable.flag_cr),
    Country("Croatia", "+385", "HR", R.drawable.flag_hr),
    Country("Cuba", "+53", "CU", R.drawable.flag_cu),
    Country("Curaçao", "+599", "CW", R.drawable.flag_cw),
    Country("Cyprus", "+357", "CY", R.drawable.flag_cy),
    Country("Czechia", "+420", "CZ", R.drawable.flag_cz),
    Country("Côte d'Ivoire", "+225", "CI", R.drawable.flag_ci),
    Country("Denmark", "+45", "DK", R.drawable.flag_dk),
    Country("Djibouti", "+253", "DJ", R.drawable.flag_dj),
    Country("Dominica", "+1-767", "DM", R.drawable.flag_dm),
    Country("Dominican Republic (the)", "+11-809, 1-829, 1-849", "DO", R.drawable.flag_do),
    Country("Ecuador", "+593", "EC", R.drawable.flag_ec),
    Country("Egypt", "+20", "EG", R.drawable.flag_eg),
    Country("El Salvador", "+503", "SV", R.drawable.flag_sv),
    Country("Equatorial Guinea", "+240", "GQ", R.drawable.flag_gq),
    Country("Eritrea", "+291", "ER", R.drawable.flag_er),
    Country("Estonia", "+372", "EE", R.drawable.flag_ee),
    Country("Eswatini", "+268", "SZ", R.drawable.flag_sz),
    Country("Ethiopia", "+251", "ET", R.drawable.flag_et),
    Country("Falkland Islands (the) [Malvinas]", "+500", "FK", R.drawable.flag_fk),
    Country("Faroe Islands (the)", "+298", "FO", R.drawable.flag_fo),
    Country("Fiji", "+679", "FJ", R.drawable.flag_fj),
    Country("Finland", "+358", "FI", R.drawable.flag_fi),
    Country("France", "+33", "FR", R.drawable.flag_fr),
    Country("French Guiana", "+594", "GF", R.drawable.flag_gf),
    Country("French Polynesia", "+689", "PF", R.drawable.flag_pf),
    Country("French Southern Territories (the)", "+262", "TF", R.drawable.flag_tf),
    Country("Gabon", "+241", "GA", R.drawable.flag_ga),
    Country("Gambia (the)", "+220", "GM", R.drawable.flag_gm),
    Country("Georgia", "+995", "GE", R.drawable.flag_ge),
    Country("Germany", "+49", "DE", R.drawable.flag_de),
    Country("Ghana", "+233", "GH", R.drawable.flag_gh),
    Country("Gibraltar", "+350", "GI", R.drawable.flag_gi),
    Country("Greece", "+30", "GR", R.drawable.flag_gr),
    Country("Greenland", "+299", "GL", R.drawable.flag_gl),
    Country("Grenada", "+1-473", "GD", R.drawable.flag_gd),
    Country("Guadeloupe", "+590", "GP", R.drawable.flag_gp),
    Country("Guam", "+1-671", "GU", R.drawable.flag_gu),
    Country("Guatemala", "+502", "GT", R.drawable.flag_gt),
    Country("Guernsey", "+44-1481", "GG", R.drawable.flag_gg),
    Country("Guinea", "+224", "GN", R.drawable.flag_gn),
    Country("Guinea-Bissau", "+245", "GW", R.drawable.flag_gw),
    Country("Guyana", "+592", "GY", R.drawable.flag_gy),
    Country("Haiti", "+509", "HT", R.drawable.flag_ht),
    Country("Heard Island and McDonald Islands", "+672", "HM", R.drawable.flag_hm),
    Country("Holy See (the)", "+379", "VA", R.drawable.flag_va),
    Country("Honduras", "+504", "HN", R.drawable.flag_hn),
    Country("Hong Kong", "+852", "HK", R.drawable.flag_hk),
    Country("Hungary", "+36", "HU", R.drawable.flag_hu),
    Country("Iceland", "+354", "IS", R.drawable.flag_is),
    Country("India", "+91", "IN", R.drawable.flag_in),
    Country("Indonesia", "+62", "ID", R.drawable.flag_id),
    Country("Iran (Islamic Republic of)", "+98", "IR", R.drawable.flag_ir),
    Country("Iraq", "+964", "IQ", R.drawable.flag_iq),
    Country("Ireland", "+353", "IE", R.drawable.flag_ie),
    Country("Isle of Man", "+44-1624", "IM", R.drawable.flag_im),
    Country("Israel", "+972", "IL", R.drawable.flag_il),
    Country("Italy", "+39", "IT", R.drawable.flag_it),
    Country("Jamaica", "+1-876", "JM", R.drawable.flag_jm),
    Country("Japan", "+81", "JP", R.drawable.flag_jp),
    Country("Jersey", "+44-1534", "JE", R.drawable.flag_je),
    Country("Jordan", "+962", "JO", R.drawable.flag_jo),
    Country("Kazakhstan", "+7", "KZ", R.drawable.flag_kz),
    Country("Kenya", "+254", "KE", R.drawable.flag_ke),
    Country("Kiribati", "+686", "KI", R.drawable.flag_ki),
    Country("Korea (North)", "+850", "KP", R.drawable.flag_kp),
    Country("Korea (South)", "+82", "KR", R.drawable.flag_kr),
    Country("Kosovo", "+383", "XK", R.drawable.flag_xk),
    Country("Kuwait", "+965", "KW", R.drawable.flag_kw),
    Country("Kyrgyzstan", "+996", "KG", R.drawable.flag_kg),
    Country("Lao People's Democratic Republic (the)", "+856", "LA", R.drawable.flag_la),
    Country("Latvia", "+371", "LV", R.drawable.flag_lv),
    Country("Lebanon", "+961", "LB", R.drawable.flag_lb),
    Country("Lesotho", "+266", "LS", R.drawable.flag_ls),
    Country("Liberia", "+231", "LR", R.drawable.flag_lr),
    Country("Libya", "+218", "LY", R.drawable.flag_ly),
    Country("Liechtenstein", "+423", "LI", R.drawable.flag_li),
    Country("Lithuania", "+370", "LT", R.drawable.flag_lt),
    Country("Luxembourg", "+352", "LU", R.drawable.flag_lu),
    Country("Macao", "+853", "MO", R.drawable.flag_mo),
    Country("Madagascar", "+261", "MG", R.drawable.flag_mg),
    Country("Malawi", "+265", "MW", R.drawable.flag_mw),
    Country("Malaysia", "+60", "MY", R.drawable.flag_my),
    Country("Maldives", "+960", "MV", R.drawable.flag_mv),
    Country("Mali", "+223", "ML", R.drawable.flag_ml),
    Country("Malta", "+356", "MT", R.drawable.flag_mt),
    Country("Marshall Islands (the)", "+692", "MH", R.drawable.flag_mh),
    Country("Martinique", "+596", "MQ", R.drawable.flag_mq),
    Country("Mauritania", "+222", "MR", R.drawable.flag_mr),
    Country("Mauritius", "+230", "MU", R.drawable.flag_mu),
    Country("Mayotte", "+262", "YT", R.drawable.flag_yt),
    Country("Mexico", "+52", "MX", R.drawable.flag_mx),
    Country("Micronesia (Federated States of)", "+691", "FM", R.drawable.flag_fm),
    Country("Moldova (the Republic of)", "+373", "MD", R.drawable.flag_md),
    Country("Monaco", "+377", "MC", R.drawable.flag_mc),
    Country("Mongolia", "+976", "MN", R.drawable.flag_mn),
    Country("Montenegro", "+382", "ME", R.drawable.flag_me),
    Country("Montserrat", "+1-664", "MS", R.drawable.flag_ms),
    Country("Morocco", "+212", "MA", R.drawable.flag_ma),
    Country("Mozambique", "+258", "MZ", R.drawable.flag_mz),
    Country("Myanmar", "+95", "MM", R.drawable.flag_mm),
    Country("Namibia", "+264", "NA", R.drawable.flag_na),
    Country("Nauru", "+674", "NR", R.drawable.flag_nr),
    Country("Nepal", "+977", "NP", R.drawable.flag_np),
    Country("Netherlands (Kingdom of the)", "+31", "NL", R.drawable.flag_nl),
    Country("New Caledonia", "+687", "NC", R.drawable.flag_nc),
    Country("New Zealand", "+64", "NZ", R.drawable.flag_nz),
    Country("Nicaragua", "+505", "NI", R.drawable.flag_ni),
    Country("Niger (the)", "+227", "NE", R.drawable.flag_ne),
    Country("Nigeria", "+234", "NG", R.drawable.flag_ng),
    Country("Niue", "+683", "NU", R.drawable.flag_nu),
    Country("Norfolk Island", "+672", "NF", R.drawable.flag_nf),
    Country("North Macedonia", "+389", "MK", R.drawable.flag_mk),
    Country("Northern Mariana Islands (the)", "+1-670", "MP", R.drawable.flag_mp),
    Country("Norway", "+47", "NO", R.drawable.flag_no),
    Country("Oman", "+968", "OM", R.drawable.flag_om),
    Country("Pakistan", "+92", "PK", R.drawable.flag_pk),
    Country("Palau", "+680", "PW", R.drawable.flag_pw),
    Country("Palestine, State of", "+970", "PS", R.drawable.flag_ps),
    Country("Panama", "+507", "PA", R.drawable.flag_pa),
    Country("Papua New Guinea", "+675", "PG", R.drawable.flag_pg),
    Country("Paraguay", "+595", "PY", R.drawable.flag_py),
    Country("Peru", "+51", "PE", R.drawable.flag_pe),
    Country("Philippines (the)", "+63", "PH", R.drawable.flag_ph),
    Country("Pitcairn", "+64", "PN", R.drawable.flag_pn),
    Country("Poland", "+48", "PL", R.drawable.flag_pl),
    Country("Portugal", "+351", "PT", R.drawable.flag_pt),
    Country("Puerto Rico", "+1", "PR", R.drawable.flag_pr),
    Country("Qatar", "+974", "QA", R.drawable.flag_qa),
    Country("Romania", "+40", "RO", R.drawable.flag_ro),
    Country("Russian Federation (the)", "+7", "RU", R.drawable.flag_ru),
    Country("Rwanda", "+250", "RW", R.drawable.flag_rw),
    Country("Réunion", "+262", "RE", R.drawable.flag_re),
    Country("Saint Barthélemy", "+590", "BL", R.drawable.flag_bl),
    Country("Saint Helena, Ascension and Tristan da Cunha", "+290", "SH", R.drawable.flag_sh),
    Country("Saint Kitts and Nevis", "+1", "KN", R.drawable.flag_kn),
    Country("Saint Lucia", "+1", "LC", R.drawable.flag_lc),
    Country("Saint Martin", "+590", "MF", R.drawable.flag_mf),
    Country("Saint Pierre and Miquelon", "+508", "PM", R.drawable.flag_pm),
    Country("Saint Vincent and the Grenadines", "+1", "VC", R.drawable.flag_vc),
    Country("Samoa", "+685", "WS", R.drawable.flag_ws),
    Country("San Marino", "+378", "SM", R.drawable.flag_sm),
    Country("Sao Tome and Principe", "+239", "ST", R.drawable.flag_st),
    Country("Saudi Arabia", "+966", "SA", R.drawable.flag_sa),
    Country("Senegal", "+221", "SN", R.drawable.flag_sn),
    Country("Serbia", "+381", "RS", R.drawable.flag_rs),
    Country("Seychelles", "+248", "SC", R.drawable.flag_sc),
    Country("Sierra Leone", "+232", "SL", R.drawable.flag_sl),
    Country("Singapore", "+65", "SG", R.drawable.flag_sg),
    Country("Sint Maarten (Dutch part)", "+1-721", "SX", R.drawable.flag_sx),
    Country("Slovakia", "+421", "SK", R.drawable.flag_sk),
    Country("Slovenia", "+386", "SI", R.drawable.flag_si),
    Country("Solomon Islands", "+677", "SB", R.drawable.flag_sb),
    Country("Somalia", "+252", "SO", R.drawable.flag_so),
    Country("South Africa", "+27", "ZA", R.drawable.flag_za),
    Country("South Georgia and the South Sandwich Islands", "+500", "GS", R.drawable.flag_gs),
    Country("South Sudan", "+211", "SS", R.drawable.flag_ss),
    Country("Spain", "+34", "ES", R.drawable.flag_es),
    Country("Sri Lanka", "+94", "LK", R.drawable.flag_lk),
    Country("Sudan (the)", "+249", "SD", R.drawable.flag_sd),
    Country("Suriname", "+597", "SR", R.drawable.flag_sr),
    Country("Svalbard and Jan Mayen", "+47", "SJ", R.drawable.flag_sj),
    Country("Sweden", "+46", "SE", R.drawable.flag_se),
    Country("Switzerland", "+41", "CH", R.drawable.flag_ch),
    Country("Syrian Arab Republic (the)", "+963", "SY", R.drawable.flag_sy),
    Country("Taiwan", "+886", "TW", R.drawable.flag_tw),
    Country("Tajikistan", "+992", "TJ", R.drawable.flag_tj),
    Country("Tanzania", "+255", "TZ", R.drawable.flag_tz),
    Country("Thailand", "+66", "TH", R.drawable.flag_th),
    Country("Timor-Leste", "+670", "TL", R.drawable.flag_tl),
    Country("Togo", "+228", "TG", R.drawable.flag_tg),
    Country("Tokelau", "+690", "TK", R.drawable.flag_tk),
    Country("Tonga", "+676", "TO", R.drawable.flag_to),
    Country("Trinidad and Tobago", "+1-868", "TT", R.drawable.flag_tt),
    Country("Tunisia", "+216", "TN", R.drawable.flag_tn),
    Country("Turkey", "+90", "TR", R.drawable.flag_tr),
    Country("Turkmenistan", "+993", "TM", R.drawable.flag_tm),
    Country("Turks and Caicos Islands (the)", "+1-649", "TC", R.drawable.flag_tc),
    Country("Tuvalu", "+688", "TV", R.drawable.flag_tv),
    Country("Uganda", "+256", "UG", R.drawable.flag_ug),
    Country("Ukraine", "+380", "UA", R.drawable.flag_ua),
    Country("United Arab Emirates (the)", "+971", "AE", R.drawable.flag_ae),
    Country("United Kingdom", "+44", "GB", R.drawable.flag_gb),
    Country("United States Minor Outlying Islands (the)", "+246", "UM", R.drawable.flag_um),
    Country("United States of America (the)", "+1", "US", R.drawable.flag_us),
    Country("Uruguay", "+598", "UY", R.drawable.flag_uy),
    Country("Uzbekistan", "+998", "UZ", R.drawable.flag_uz),
    Country("Vanuatu", "+678", "VU", R.drawable.flag_vu),
    Country("Venezuela", "+58", "VE", R.drawable.flag_ve),
    Country("Viet Nam", "+84", "VN", R.drawable.flag_vn),
    Country("Virgin Islands (British)", "+1-284", "VG", R.drawable.flag_vg),
    Country("Virgin Islands (U.S.)", "+1-340", "VI", R.drawable.flag_vi),
    Country("Wallis and Futuna", "+681", "WF", R.drawable.flag_wf),
    Country("Western Sahara", "+212", "EH", R.drawable.flag_eh),
    Country("Yemen", "+967", "YE", R.drawable.flag_ye),
    Country("Zambia", "+260", "ZM", R.drawable.flag_zm),
    Country("Zimbabwe", "+263", "ZW", R.drawable.flag_zw),
  )
}