name: Unit Testing

on:
  push:
    paths-ignore:
      - 'CONTRIBUTING.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'CONTRIBUTING.md'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run unit test app
        run: ./gradlew testDebugUnitTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-reports
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Build with Gradle Wrapper
        run: ./gradlew assembleDebug --stacktrace
